version: '3.8'
services:
  app:
    build:
      context: ./TicTacToe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - GameSettings__WinCondition=3
      - GameSettings__BoardSize=5
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: